name: .NET

on:
  
  push:
    branches:
    - master
  
jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
      
    - name: Publish Abstractions (on version change)
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: FineDataFlow.Engine.Abstractions/10.FineDataFlow.Engine.Abstractions.csproj
        PACKAGE_NAME: FineDataFlow.Engine
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: false

    - name: Publish Main (on version change)
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: FineDataFlow.Engine/30.FineDataFlow.Engine.csproj
        PACKAGE_NAME: FineDataFlow.Engine
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: false